name: Create New DEEP
description: https://experience.donedone.me/#deep
body:
  - type: checkboxes
    attributes:
      label: 체크리스트
      options:
        - label: 제목을 입력하셨나요?
          required: true
        - label: Assignee를 지정하셨나요?
          required: true
        - label: 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)
          required: true
  - type: textarea
    attributes:
      label: 요약
      description: (셍략 가능)
    validations:
      required: false
  - type: textarea
    attributes:
      label: 필요한 이유
      description: (`product` 유형은 생략 가능)
    validations:
      required: false
  - type: textarea
    attributes:
      label: 목표
      description: (필수)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 추후 목표
      description: (생략 가능)
    validations:
      required: false
  - type: textarea
    attributes:
      label: 계획
      description: (필수)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 논의 사항
      description: (생략 가능)
    validations:
      required: false
